const ENDPOINT = 'http://86.218.243.242:8000/api/';
const ENDPOINT_CONCERT = ENDPOINT + 'concerts/';
const ENDPOINT_ALBUMS = ENDPOINT + 'albums/';
const ENDPOINT_GROUPES = ENDPOINT + 'groupes/';
const ENDPOINT_FESTIVALS = ENDPOINT + 'festivals/';
const ENDPOINT_INFOS = ENDPOINT + 'infos/';





export { ENDPOINT_CONCERT, ENDPOINT_ALBUMS, ENDPOINT_GROUPES, ENDPOINT_FESTIVALS, ENDPOINT_INFOS };
